---
#curl -H "X-Auth-Token: ${SCALEWAY_SECRET_KEY}" https://api.scaleway.com/instance/v1/zones/nl-ams-1/images | jq
#curl -H "X-Auth-Token: ${SCALEWAY_SECRET_KEY}" https://api.scaleway.com/instance/v1/zones/fr-par-1/images | jq
# https://www.scaleway.com/en/docs/interact-with-the-compute-api/
- name: Scaleway
  hosts: par1
  gather_facts: yes

  tasks:
    - debug: var=hostvars[inventory_hostname]['public_ipv4']

#    - name: Create a server
#      scaleway_compute:
#        name: nexus-test
#        state: present
#        image: 98cdcaef-ed64-45b5-8b12-a7a2b3f1e454  # "Ubuntu 20.04 Focal Fossa"
#        organization: "{{ SCALEWAY_ORGANIZATION_ID }}"
#        region: par1
#        commercial_type: DEV1-S
#        enable_ipv6: yes
#        public_ip: dynamic
#        tags:
#          - test
#          - nexus
#      register: server_creation_task
#
#    - debug: var=server_creation_task
#
#    - assert:
#        that:
#          - server_creation_task is success
#          - server_creation_task is changed
#
#    - name: Run it
#      scaleway_compute:
#        name: nexus-test
#        state: running
#        image: 98cdcaef-ed64-45b5-8b12-a7a2b3f1e454  # "Ubuntu 20.04 Focal Fossa"
#        organization: "{{ SCALEWAY_ORGANIZATION_ID }}"
#        region: par1
#        commercial_type: DEV1-S
#        wait: true
#        tags:
#          - test
#          - nexus
#      register: server_run_task
#
#    - debug: var=server_run_task
#    - debug: var=server_run_task.msg.public_ip
#
#
#    - assert:
#        that:
#          - server_run_task is success
#          - server_run_task is changed
